### ISSUE TITLE
SSF-morph handling the neg_log_10_p_value

### ISSUE THREAD

**Issue by jiyue1214** [EBISPOT/gwas-sumstats-tools#43]
- Bug: When setting the `"convertNegLog10Pvalue": true` and clicking the `test` button, the `neg_log_10_p_value` was not converted into p_value on the UI side
- Reason: convertNegLog10Pvalue function was implemented to the apply_config function, but not the test_config function
- [x] Solution: add this function to the test_config

Enhancement: gwas-sumstat-tools-Documentation formatting needs an example to introduce how to handle neg_log_10_p_value in the input data 
- [x] Solution: add an example on the Documentation

**Comment by jiyue1214** [comment]
It caused by the `neg_log_10_p_value` did not included in the test function. I have implemented it for SSF-morph. Santhi will test it when she has time. It can be moved to the review.

**Comment by jiyue1214** [comment]
@Santhi1901, Could you please help me to check if the issue is solved? Thanks!

**Comment by Santhi1901** [comment]
tested and it worked all fine
